### ISSUE TITLE
ERROR: List index out of range

### ISSUE THREAD

**Issue by Woisek** [kohya-ss/sd-webui-additional-networks#116]
Right after a fresh start of WebUI, I get this error:

Error executing callback ui_tabs_callback for I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "I:\Super SD 2.0\stable-diffusion-webui\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 232, in on_ui_tabs
    metadata_editor.setup_ui(addnet_paste_params)
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py", line 384, in setup_ui
    send_to_button.click(fn=lambda modu, mod: (modu, model_util.find_closest_lora_model_name(mod) or "None"), inputs=[module, model], outputs=[addnet_paste_params[tabname][i]["module"], addnet_paste_params[tabname][i]["model"]])
IndexError: list index out of range

Error executing callback ui_tabs_callback for I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "I:\Super SD 2.0\stable-diffusion-webui\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 232, in on_ui_tabs
    metadata_editor.setup_ui(addnet_paste_params)
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py", line 384, in setup_ui
    send_to_button.click(fn=lambda modu, mod: (modu, model_util.find_closest_lora_model_name(mod) or "None"), inputs=[module, model], outputs=[addnet_paste_params[tabname][i]["module"], addnet_paste_params[tabname][i]["model"]])
IndexError: list index out of range

Running on local URL:  http://127.0.0.1:7860

Any ideas?

**Comment by Narex1158** [comment]
I got the same error after the installation. Any clue?

**Comment by zhengquan45** [comment]
I also encountered it.
