### ISSUE TITLE
Changing folder causes error?

### ISSUE THREAD

**Issue by poisenbery** [kohya-ss/sd-webui-additional-networks#135]
I changed the folder path for finding LORA in the settings to look at the LORA folder in the stable diffusion directory.

I suspect that there is a LORA somewhere causing the issue, but I have a few hundred of these files, and I'm not sure which one might be causing this.

I am now getting an error loop. It will update model hashes, error at a certain point, and then repeat the process around 4-5 times. Starting the WebUI takes ~5 minutes now, compared to ~15 seconds before.

The Additional Networks tab is not displayed when the Web UI finally loads.

``` 
Error loading script: additional_networks.py
Traceback (most recent call last):
  File "V:\AI\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "V:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "V:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 11, in <module>
    from scripts import lora_compvis, model_util, metadata_editor, xyz_grid_support
  File "V:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 323, in <module>
    update_models()
  File "V:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 307, in update_models
    res, res_legacy = get_all_models(paths, sort_by, filter_by)
  File "V:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 207, in get_all_models
    for res in p.imap_unordered(hash_model_file, fileinfos):
  File "C:\Users\austi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 873, in next
    raise value
  File "C:\Users\austi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "V:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 175, in hash_model_file
    metadata = safetensors_hack.read_metadata(filename)
  File "V:\AI\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 22, in read_metadata
    metadata = json.loads(metadata_bytes)
  File "C:\Users\austi\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
  File "C:\Users\austi\AppData\Local\Programs\Python\Python310\lib\encodings\utf_32_be.py", line 11, in decode
    return codecs.utf_32_be_decode(input, errors, True)
UnicodeDecodeError: 'utf-32-be' codec can't decode bytes in position 20-23: code point not in range(0x110000)
```

I have no idea what to do.

**Comment by poisenbery** [comment]
I wasn't on latest commit. My bad
