### ISSUE TITLE
Additional Network extension not installed, Only hijack built-in lora LoCon Extension hijack built-in lora successfully

### ISSUE THREAD

**Issue by randomuser11956** [kohya-ss/sd-webui-additional-networks#139]
Hello, i get this thing when i run stable diffusion webui and don't know what it means... Is it bad? Did something break?
All my loras work... well now, first all of the gave errors
Error running process_batch: C:\Users\me\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "C:\Users\me\stable-diffusion-webui\modules\scripts.py", line 427, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "C:\Users\me\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 209, in process_batch
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight_tenc, weight_unet, text_encoder, unet)
  File "C:\Users\me\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 102, in create_network_and_apply_compvis
    state_dict = network.apply_lora_modules(du_state_dict)              # some weights are applied to text encoder
  File "C:\Users\me\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 289, in apply_lora_modules
    state_dict = LoRANetworkCompvis.convert_state_dict_name_to_compvis(self.v2, du_state_dict)
  File "C:\Users\me\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 193, in convert_state_dict_name_to_compvis
    compvis_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(v2, tokens[0])
  File "C:\Users\me\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 182, in convert_diffusers_name_to_compvis
    assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by sd-scripts."
AssertionError: conversion failed: lora_unetdown

but afterwards i used git pull command in the extension folder and my loras still did not work
then i used pip install -r requirements.txt in the sd folder
after this install i managed to make my loras work. BUT i still get this thing in my command prompt when i run sd
loras work when i enable them in the additional networks drop down menu

this happened when i updated to torch 2 and changed some requirements like accelerate and transformers version.
now i have xformers==0.0.17.dev476,  torch: 1.13.1+cu117 and transformers==4.25.1 accelerate==0.12.0

**Comment by kohya-ss** [comment]
This error seems to be output by LyCORIS web UI extension. Unfortunately LyCORIS models are not supported by this extension currently. I'd like to support them in future.

**Comment by bignewbee** [comment]
thank you!
