### ISSUE TITLE
i got this error when running addtional network

### ISSUE THREAD

**Issue by Darelllf** [kohya-ss/sd-webui-additional-networks#140]
i got 2 error when run additional network

LoRA weight_unet: 1, weight_tenc: 1, model: mymodel(45f1f5900b9e)
dimension: {13, 18, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 40, 41, 42, 43, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60, 61, 62, 63, 65, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 89, 90, 94, 96, 97, 98, 99, 100, 101, 103, 105, 106, 108, 109, 111, 112, 115, 116, 117, 118, 120, 121, 123, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 140, 141, 142, 143, 144, 145, 147, 149, 150, 151, 152, 154, 155, 156, 157, 158, 160, 161, 162, 163, 164, 165, 166, 168, 169, 170, 171, 172, 174, 175, 177, 178, 179, 180, 181, 182, 183, 185, 190, 191, 192, 193, 195, 196, 197, 200, 202, 204, 205, 208, 209, 211, 212, 214, 219, 222, 223, 225, 228, 229, 235, 236, 241, 242, 246, 249, 250, 254, 255, 256, 257, 259, 261, 262, 263, 266, 269, 270, 271, 272, 275, 277, 280, 282, 285, 287, 291, 292, 294, 298, 315, 325, 331, 341, 348, 355, 358, 360, 362, 371, 374, 377, 378, 394, 397, 401, 423}, alpha: {13.0, 18.0, 22.0, 23.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 34.0, 35.0, 40.0, 41.0, 42.0, 43.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 60.0, 61.0, 62.0, 63.0, 65.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 89.0, 90.0, 94.0, 96.0, 97.0, 98.0, 99.0, 100.0, 101.0, 103.0, 105.0, 106.0, 108.0, 109.0, 111.0, 112.0, 115.0, 116.0, 117.0, 118.0, 120.0, 121.0, 123.0, 125.0, 126.0, 127.0, 128.0, 129.0, 130.0, 131.0, 132.0, 133.0, 134.0, 135.0, 136.0, 137.0, 138.0, 140.0, 141.0, 142.0, 143.0, 144.0, 145.0, 147.0, 149.0, 150.0, 151.0, 152.0, 154.0, 155.0, 156.0, 157.0, 158.0, 160.0, 161.0, 162.0, 163.0, 164.0, 165.0, 166.0, 168.0, 169.0, 170.0, 171.0, 172.0, 174.0, 175.0, 177.0, 178.0, 179.0, 180.0, 181.0, 182.0, 183.0, 185.0, 190.0, 191.0, 192.0, 193.0, 195.0, 196.0, 197.0, 200.0, 202.0, 204.0, 205.0, 208.0, 209.0, 211.0, 212.0, 214.0, 219.0, 222.0, 223.0, 225.0, 228.0, 229.0, 235.0, 236.0, 241.0, 242.0, 246.0, 249.0, 250.0, 254.0, 255.0, 256.0, 257.0, 259.0, 261.0, 262.0, 263.0, 266.0, 269.0, 270.0, 271.0, 272.0, 275.0, 277.0, 280.0, 282.0, 285.0, 287.0, 291.0, 292.0, 294.0, 298.0, 315.0, 325.0, 331.0, 341.0, 348.0, 355.0, 358.0, 360.0, 362.0, 371.0, 374.0, 377.0, 378.0, 394.0, 397.0, 401.0, 423.0}, multiplier_unet: 1, multiplier_tenc: 1
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 278 modules.
original forward/weights is backed up.
enable LoRA for text encoder
enable LoRA for U-Net
Error running process_batch: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 220, in process_batch
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight_tenc, weight_unet, text_encoder, unet)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 150, in create_network_and_apply_compvis
    state_dict = network.apply_lora_modules(du_state_dict)              # some weights are applied to text encoder
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 521, in apply_lora_modules
    state_dict = self.convert_state_dict_shape_to_compvis(state_dict)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 543, in convert_state_dict_shape_to_compvis
    value = value.unsqueeze(2).unsqueeze(3)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

and this error

Error completing request
Arguments: ('task(1lygcjauv8u5ctr)', 'my prompt write in this + neg prompt too', [], 38, 7, False, False, 10, 1, 7.5, -1.0, -1.0, 0, 0, 0, False, 1200, 760, True, 0.7, 1, 'None', 0, 0, 0, [], 0, True, False, 'LoRA', 'mymodel(45f1f5900b9e)', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.external_code.ControlNetUnit object at 0x7f6aca7cad90>, False, False, 'positive', 'comma', 0, False, False, '', '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, 50) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 621, in process_images_inner
    uc = get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, p.steps, cached_uc)
  File "/content/stable-diffusion-webui/modules/processing.py", line 570, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps)
  File "/content/stable-diffusion-webui/modules/prompt_parser.py", line 140, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 669, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/modules/sd_hijack_clip.py", line 229, in forward
    z = self.process_tokens(tokens, multipliers)
  File "/content/stable-diffusion-webui/modules/sd_hijack_clip.py", line 254, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "/content/stable-diffusion-webui/modules/sd_hijack_clip.py", line 302, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 811, in forward
    return self.text_model(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 721, in forward
    encoder_outputs = self.encoder(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 650, in forward
    layer_outputs = encoder_layer(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 379, in forward
    hidden_states, attn_weights = self.self_attn(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 268, in forward
    query_states = self.q_proj(hidden_states) * self.scale
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 90, in forward
    return self.org_forward(x) + self.lora_up(self.lora_down(x)) * self.multiplier * self.scale
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 178, in lora_Linear_forward
    return lora_forward(self, input, torch.nn.Linear_forward_before_lora(self, input))
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_mm)

thanks if you can solve this

**Comment by kohya-ss** [comment]
Unfortunately I cannot reproduce the issue. The model trained without 'networks.lora' (LyCORIS/LoCon/LoHA) is not supported with this extension. If not, could you share the model causes the issue?
