### ISSUE TITLE
there are no lora tab in stable diffusion webui

### ISSUE THREAD

**Issue by dankyu0514** [kohya-ss/sd-webui-additional-networks#146]
Error loading script: lora_script.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/scripts/lora_script.py", line 4, in <module>
    import lora
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 238, in <module>
    def lora_apply_weights(self: torch.nn.Conv2d | torch.nn.Linear | torch.nn.MultiheadAttention):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

how can I solve this problem?

**Comment by momoko12342** [comment]
same issue

**Comment by laksjdjf** [comment]
This is a problem with the webui builtin extension, not this repository.
It appears to have been fixed.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9017/files
