### ISSUE TITLE
[ERROR]Input and output sizes should be greater than 0, but got input (H: 512, W: 512) output (H: 0, W: 0)

### ISSUE THREAD

**Issue by mlwei1** [kohya-ss/sd-webui-additional-networks#160]
RuntimeError: Input and output sizes should be greater than 0, but got input (H: 512, W: 512) output (H: 0, W: 0)

 I enable the additional network,and 1 controlnet openpose, and get shit error,

2 lora are loaded in additional network,

weight is    0.9 and 1

mask is red and green

**Comment by zopi4k** [comment]
I have the same error,  I think it's ControlNet update ... 

> Error running process_batch: D:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
File "D:\stable-diffusion-webui\modules\scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 268, in process_batch
    network.set_mask(mask, height=p.height, width=p.width, hr_height=p.hr_upscale_to_y, hr_width=p.hr_upscale_to_x)
  File "D:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 623, in set_mask
    resize_add(h, w)
  File "D:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 615, in resize_add
    m = torch.nn.functional.interpolate(mask, (mh, mw), mode="bilinear")  # doesn't work in bf16
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\functional.py", line 3950, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: Input and output sizes should be greater than 0, but got input (H: 1066, W: 1066) output (H: 0, W: 0)

**Comment by Tom1123456** [comment]
I would like to know whether you have solved this problem. I also met the same problem recently, and I would like to consult the specific solution measures. Thank you in advance.
