### ISSUE TITLE
XYZ Plot no longer working since Automatic Torch 2.0 update

### ISSUE THREAD

**Issue by rushuna86** [kohya-ss/sd-webui-additional-networks#166]
XYZ Plot for lora throwing up errors since Automatic1111 commits for Commit for Torch 2.0

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\SD\WebUIX\venv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
ValueError: dictionary update sequence element #0 has length 31; 2 is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\WebUIX\venv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\SD\WebUIX\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\SD\WebUIX\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\SD\WebUIX\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "D:\SD\WebUIX\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\SD\WebUIX\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\SD\WebUIX\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\SD\WebUIX\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "D:\SD\WebUIX\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\SD\WebUIX\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\SD\WebUIX\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\SD\WebUIX\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\SD\WebUIX\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\SD\WebUIX\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\SD\WebUIX\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\SD\WebUIX\venv\lib\site-packages\fastapi\routing.py", line 255, in app
    content = await serialize_response(
  File "D:\SD\WebUIX\venv\lib\site-packages\fastapi\routing.py", line 152, in serialize_response
    return jsonable_encoder(response_content)
  File "D:\SD\WebUIX\venv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "D:\SD\WebUIX\venv\lib\site-packages\fastapi\encoders.py", line 131, in jsonable_encoder
    jsonable_encoder(
  File "D:\SD\WebUIX\venv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "D:\SD\WebUIX\venv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [ValueError('dictionary update sequence element #0 has length 31; 2 is required'), TypeError('vars() argument must have __dict__ attribute')]

**Comment by FerryHuang** [comment]
seems same issue:)

**Comment by kohya-ss** [comment]
The latest update might solve the issue. Please update and try again :)

**Comment by rushuna86** [comment]
ohhh i forgot to closed, i saw the new commit n it's been fixed.
