### ISSUE TITLE
Excuse me, when I updated today, the additional networks tab disappeared.

### ISSUE THREAD

**Issue by HakkaBats** [kohya-ss/sd-webui-additional-networks#193]
![Z@ %}63CPN {XX9RBI 84C](https://github.com/kohya-ss/sd-webui-additional-networks/assets/111224340/1051da0b-36a6-4947-84d5-66994e4362a8)
![GVCLTVVA4N0R`EAAIR4(LNS](https://github.com/kohya-ss/sd-webui-additional-networks/assets/111224340/032cd01b-8d44-44a2-bc8e-0d52deb1f0e9)
![%5QKYKD7H2D5WX(DB3 888Y](https://github.com/kohya-ss/sd-webui-additional-networks/assets/111224340/e27055c8-7303-4e23-b8b2-50bd1071fa04)
![Z6J3$HP653X}ADS1_$8 W`A](https://github.com/kohya-ss/sd-webui-additional-networks/assets/111224340/cf3a3bb8-7005-415c-8b59-dcefae159330)
And the Network module changed from 5 to 1.

**Comment by HakkaBats** [comment]
![H`2$B$R@9`3SK%VT5Q5QB{O](https://github.com/kohya-ss/sd-webui-additional-networks/assets/111224340/35720b90-a459-425d-af2f-2dfe582733e4)

**Comment by kohya-ss** [comment]
The tabs seem to be displayed in my env. Can you share the error message in the console?

**Comment by elviola9029** [comment]
Same problem using Google colab today.

**Comment by hanajisensei** [comment]
Here's an error I encountered when using it via Google Colab: 
![Error Additional Networks](https://github.com/kohya-ss/sd-webui-additional-networks/assets/134468332/55567f7c-b6c3-4308-846b-a8b0f53fe646)

**Comment by AtidC** [comment]
**Error message while install**
```
Error calling: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py/ui
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 104, in ui
    weight.release(lambda w: (w, w), inputs=[weight], outputs=[weight_unet, weight_tenc])
AttributeError: 'Slider' object has no attribute 'release'
```

**Comment by Dokumento1313** [comment]
Hi! Nice to meet you. I've been trying to use your extension for several days, I had used it before and it worked wonderfully, but in the past days I get this error and now it's impossible to load the LoRA that I want to use.

```
Error calling: /content/sd-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py/ui
Traceback (most recent call last):
  File "/content/sd-webui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/content/sd-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 104, in ui
    weight.release(lambda w: (w, w), inputs=[weight], outputs=[weight_unet, weight_tenc])
AttributeError: 'Slider' object has no attribute 'release'

Create LRU cache (max_size=16) for preprocessor results.
Error calling: /content/sd-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py/ui
Traceback (most recent call last):
  File "/content/sd-webui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/content/sd-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 104, in ui
    weight.release(lambda w: (w, w), inputs=[weight], outputs=[weight_unet, weight_tenc])
AttributeError: 'Slider' object has no attribute 'release'

Error executing callback ui_tabs_callback for /content/sd-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/sd-webui/modules/script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "/content/sd-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 290, in on_ui_tabs
    metadata_editor.setup_ui(addnet_paste_params)
  File "/content/sd-webui/extensions/sd-webui-additional-networks/scripts/metadata_editor.py", line 462, in setup_ui
    outputs=[addnet_paste_params[tabname][i]["module"], addnet_paste_params[tabname][i]["model"]],
IndexError: list index out of range
```

**Comment by leachyleach** [comment]
Pretty much the same problem as everyone else. Lora tabs are missing, not working, and can't be refreshed. In addition, dragging loras to SD's lora models folder and manually entering them doesn't make them work either post-update today:

```
Error calling: C:\ai\stable-diffusion-1_5\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py/ui
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-1_5\stable-diffusion-webui\modules\scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "C:\ai\stable-diffusion-1_5\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 104, in ui
    weight.release(lambda w: (w, w), inputs=[weight], outputs=[weight_unet, weight_tenc])
AttributeError: 'Slider' object has no attribute 'release'

Error executing callback ui_tabs_callback for C:\ai\stable-diffusion-1_5\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-1_5\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "C:\ai\stable-diffusion-1_5\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 290, in on_ui_tabs
    metadata_editor.setup_ui(addnet_paste_params)
  File "C:\ai\stable-diffusion-1_5\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py", line 462, in setup_ui
    outputs=[addnet_paste_params[tabname][i]["module"], addnet_paste_params[tabname][i]["model"]],
IndexError: list index out of range
```

**Comment by MuscleEnjoyer** [comment]
I am also experiencing the same issue. Just happened to me today.

Error running process_batch: D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "D:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 190, in process_batch
    if not args[0]:
IndexError: tuple index out of range

**Comment by kohya-ss** [comment]
The error seems to be caused by the lack of `release` event in Gradio's Slider. `release` event wes added in `3.20.0`. The latest Web UI uses Gradio `3.29.0`; upgrading Gradio or Web UI itself will solve this issue.

If there is any reason it cannot be updated, please let me know.

**Comment by alexonenine79** [comment]
maybe you guys haven't update your SD try update it first
open CMD
x:
cd x:\AI\stable-diffusion-webui\
git pull

**Comment by JamesMarcum** [comment]
I prefer SD 1.5,  Do I need to upgrade to 2.x for this to work again?
