### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by Romangelo** [kohya-ss/sd-webui-additional-networks#194]
Restarting UI...
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Error calling: F:\SD\extensions\sd-webui-additional-networks\scripts\additional_networks.py/ui
Traceback (most recent call last):
  File "F:\SD\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "F:\SD\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 104, in ui
    weight.release(lambda w: (w, w), inputs=[weight], outputs=[weight_unet, weight_tenc])
AttributeError: 'Slider' object has no attribute 'release'

Error calling: F:\SD\extensions\sd-webui-additional-networks\scripts\additional_networks.py/ui
Traceback (most recent call last):
  File "F:\SD\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "F:\SD\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 104, in ui
    weight.release(lambda w: (w, w), inputs=[weight], outputs=[weight_unet, weight_tenc])
AttributeError: 'Slider' object has no attribute 'release'

Error executing callback ui_tabs_callback for F:\SD\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "F:\SD\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "F:\SD\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 290, in on_ui_tabs
    metadata_editor.setup_ui(addnet_paste_params)
  File "F:\SD\extensions\sd-webui-additional-networks\scripts\metadata_editor.py", line 462, in setup_ui
    outputs=[addnet_paste_params[tabname][i]["module"], addnet_paste_params[tabname][i]["model"]],
IndexError: list index out of range

**Comment by leachyleach** [comment]
**I also got some errors when updating today that make it so loras no longer work, there is no refresh models option, and there is only one dropdown to select a model. Below are the command errors:**

Error calling: C:\ai\stable-diffusion-1_5\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py/ui
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-1_5\stable-diffusion-webui\modules\scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "C:\ai\stable-diffusion-1_5\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 104, in ui
    weight.release(lambda w: (w, w), inputs=[weight], outputs=[weight_unet, weight_tenc])
AttributeError: 'Slider' object has no attribute 'release'

Error executing callback ui_tabs_callback for C:\ai\stable-diffusion-1_5\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-1_5\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "C:\ai\stable-diffusion-1_5\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 290, in on_ui_tabs
    metadata_editor.setup_ui(addnet_paste_params)
  File "C:\ai\stable-diffusion-1_5\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py", line 462, in setup_ui
    outputs=[addnet_paste_params[tabname][i]["module"], addnet_paste_params[tabname][i]["model"]],
IndexError: list index out of range

**Comment by kohya-ss** [comment]
This may be duplicated with #193. Please try this comment: https://github.com/kohya-ss/sd-webui-additional-networks/issues/193#issuecomment-1565302366

**Comment by 2blackbar** [comment]
what up people? is this even working? what was last one that worked ?

**Comment by Romangelo** [comment]
> what up people? is this even working? what was last one that worked ?

I'm not sure. I uninstalled it and SD works just fine including LORAs. I guess the newer versions of SD already support LORAs so you don't need this.

**Comment by live106** [comment]
same problem
