### ISSUE TITLE
lora not working,I have already reinstalled the plugin, but the problem still persists.

### ISSUE THREAD

**Issue by AoyamaT1** [kohya-ss/sd-webui-additional-networks#212]
Error running process_batch: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 427, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 190, in process_batch
    if not args[0]:
IndexError: tuple index out of range

**Comment by RookieC0der11** [comment]
I just resolve that same problem by deleting some extensions, this extensions works fine

**Comment by oliverban** [comment]
> I just resolve that same problem by deleting some extensions, this extensions works fine

Do you know exactly which one it was that caused the conflict?

**Comment by RookieC0der11** [comment]
> > I just resolve that same problem by deleting some extensions, this extensions works fine
> 
> Do you know exactly which one it was that caused the conflict?

I only uninstall 2, I think it was an animation one, video2video or something, it was the one that use the "tile" open poser model to work better, search the guthub page for this word,
