### ISSUE TITLE
I got this with my own lora. I did as the tutorial on youtube but it didn't work properly

### ISSUE THREAD

**Issue by Stayer2109** [kohya-ss/sd-webui-additional-networks#213]
Error running process_batch: D:\Tools\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "D:\Tools\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 490, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "D:\Tools\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 244, in process_batch
        network, info = lora_compvis.create_network_and_apply_compvis(
      File "D:\Tools\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 153, in create_network_and_apply_compvis
        network = LoRANetworkCompvis(text_encoder, unet, multiplier_tenc, multiplier_unet, modules_dim, modules_alpha)
      File "D:\Tools\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 341, in __init__
        comp_vis_lora_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(self.v2, du_lora_name)
      File "D:\Tools\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 302, in convert_diffusers_name_to_compvis
        assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by `sd-scripts`."
    AssertionError: conversion failed: lora_te1_text_model_encoder_layers_0_mlp_fc1. the model may not be trained by `sd-scripts`.

**Comment by oliverban** [comment]
Yes, I am getting the same problem. When using the Lora in the prompt like <lora:> it works fine.
