### ISSUE TITLE
SDxl function failure, error reported, request adaptation

### ISSUE THREAD

**Issue by wzgrx** [kohya-ss/sd-webui-additional-networks#220]
*** Error running process_batch: G:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui\modules\scripts.py", line 543, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "G:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 244, in process_batch
        network, info = lora_compvis.create_network_and_apply_compvis(
      File "G:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 153, in create_network_and_apply_compvis
        network = LoRANetworkCompvis(text_encoder, unet, multiplier_tenc, multiplier_unet, modules_dim, modules_alpha)
      File "G:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 341, in __init__
        comp_vis_lora_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(self.v2, du_lora_name)
      File "G:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 302, in convert_diffusers_name_to_compvis
        assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by `sd-scripts`."
    AssertionError: conversion failed: lora_unet_input_blocks_1_0_emb_layers_1. the model may not be trained by `sd-scripts`.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by zlikwidart** [comment]
I'm having the same problem with any SDXL Lora models currently.

**Comment by sweetyshots123** [comment]
same error here. Used built-in Lora feature on stable-diffusion-webui version 1.5.1 and everything is fine. Hope will be updated to use with sdxl loras aswell. Thanks!

**Comment by werran2** [comment]
For now, you could use prompt S/R to get a SDXL lora xyz table.

**Comment by deanw1980** [comment]
Any chance of update? I really need SDXL support on  additional-networks.

**Comment by deanw1980** [comment]
Any chance of update? I really need SDXL support on additional-networks.

**Comment by cheezmil** [comment]
> For now, you could use prompt S/R to get a SDXL lora xyz table.

This method will generate one more row and one more column of graphs, which reduces efficiency and is annoying. However, using additional networks does not work, but currently this plugin cannot use the Loras of SDxl
