### ISSUE TITLE
Error at init a1111: [AddNet] Updating model hashes...

### ISSUE THREAD

**Issue by soyatlas** [kohya-ss/sd-webui-additional-networks#225]
Hi. 
I get the error when I write my LORA path files in the settings 
    "additional_networks_extra_lora_path": "J:\\stable-diffusion-webui\\models\\Lora\\",
then in the next reinit a1111 I get this error and stop the extension sd-webui-additional-network (this extension).
the log error at run a1111/webui:

[AddNet] Updating model hashes...
 68%|█████████████████████████████████████████████████████████████████████▉                                 | 963/1419 [00:06<00:02, 157.00it/s]
*** Error loading script: additional_networks.py
    Traceback (most recent call last):
      File "J:\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 13, in <module>
        from scripts import addnet_xyz_grid_support, lora_compvis, model_util, metadata_editor
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\addnet_xyz_grid_support.py", line 5, in <module>
        from scripts import model_util, util
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 338, in <module>
        update_models()
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 322, in update_models
        res, res_legacy = get_all_models(paths, sort_by, filter_by)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 211, in get_all_models
        for res in p.imap_unordered(hash_model_file, fileinfos):
      File "C:\Users\verynew\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 873, in next
        raise value
      File "C:\Users\verynew\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
        result = (True, func(*args, **kwds))
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 181, in hash_model_file
        legacy_hash = get_legacy_hash(metadata, filename)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 116, in get_legacy_hash
        return safetensors_hack.legacy_hash_file(filename)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 80, in legacy_hash_file
        tensors, metadata = load_file(filename, "cpu")
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 41, in load_file
        return {name: create_tensor(storage, info, offset) for name, info in metadata.items() if name != "__metadata__"}, md
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 41, in <dictcomp>
        return {name: create_tensor(storage, info, offset) for name, info in metadata.items() if name != "__metadata__"}, md
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 116, in create_tensor
        return torch.asarray(storage[start + offset : stop + offset], dtype=torch.uint8).view(dtype=dtype).reshape(shape).clone().detach()
    RuntimeError: self.size(-1) must be divisible by 4 to view Byte as Float (different element sizes), but got 124818

---
[AddNet] Updating model hashes...
 68%|██████████████████████████████████████████████████████████████████████▍                                 | 961/1419 [00:15<00:07, 61.71it/s]
*** Error loading script: addnet_xyz_grid_support.py
    Traceback (most recent call last):
      File "J:\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\addnet_xyz_grid_support.py", line 5, in <module>
        from scripts import model_util, util
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 338, in <module>
        update_models()
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 322, in update_models
        res, res_legacy = get_all_models(paths, sort_by, filter_by)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 211, in get_all_models
        for res in p.imap_unordered(hash_model_file, fileinfos):
      File "C:\Users\verynew\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 873, in next
        raise value
      File "C:\Users\verynew\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
        result = (True, func(*args, **kwds))
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 181, in hash_model_file
        legacy_hash = get_legacy_hash(metadata, filename)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 116, in get_legacy_hash
        return safetensors_hack.legacy_hash_file(filename)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 80, in legacy_hash_file
        tensors, metadata = load_file(filename, "cpu")
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 41, in load_file
        return {name: create_tensor(storage, info, offset) for name, info in metadata.items() if name != "__metadata__"}, md
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 41, in <dictcomp>
        return {name: create_tensor(storage, info, offset) for name, info in metadata.items() if name != "__metadata__"}, md
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 116, in create_tensor
        return torch.asarray(storage[start + offset : stop + offset], dtype=torch.uint8).view(dtype=dtype).reshape(shape).clone().detach()
    RuntimeError: self.size(-1) must be divisible by 4 to view Byte as Float (different element sizes), but got 124818

---
[AddNet] Updating model hashes...
 68%|██████████████████████████████████████████████████████████████████████▍                                 | 961/1419 [00:18<00:08, 52.01it/s]
*** Error loading script: metadata_editor.py
    Traceback (most recent call last):
      File "J:\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py", line 18, in <module>
        from scripts import safetensors_hack, model_util
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 338, in <module>
        update_models()
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 322, in update_models
        res, res_legacy = get_all_models(paths, sort_by, filter_by)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 211, in get_all_models
        for res in p.imap_unordered(hash_model_file, fileinfos):
      File "C:\Users\verynew\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 873, in next
        raise value
      File "C:\Users\verynew\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
        result = (True, func(*args, **kwds))
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 181, in hash_model_file
        legacy_hash = get_legacy_hash(metadata, filename)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 116, in get_legacy_hash
        return safetensors_hack.legacy_hash_file(filename)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 80, in legacy_hash_file
        tensors, metadata = load_file(filename, "cpu")
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 41, in load_file
        return {name: create_tensor(storage, info, offset) for name, info in metadata.items() if name != "__metadata__"}, md
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 41, in <dictcomp>
        return {name: create_tensor(storage, info, offset) for name, info in metadata.items() if name != "__metadata__"}, md
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 116, in create_tensor
        return torch.asarray(storage[start + offset : stop + offset], dtype=torch.uint8).view(dtype=dtype).reshape(shape).clone().detach()
    RuntimeError: self.size(-1) must be divisible by 4 to view Byte as Float (different element sizes), but got 124818

---
[AddNet] Updating model hashes...
 68%|██████████████████████████████████████████████████████████████████████▍                                 | 961/1419 [00:32<00:15, 29.14it/s]
*** Error loading script: model_util.py
    Traceback (most recent call last):
      File "J:\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 12, in <module>
        from scripts import safetensors_hack, model_util, util
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 338, in <module>
        update_models()
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 322, in update_models
        res, res_legacy = get_all_models(paths, sort_by, filter_by)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 211, in get_all_models
        for res in p.imap_unordered(hash_model_file, fileinfos):
      File "C:\Users\verynew\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 873, in next
        raise value
      File "C:\Users\verynew\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
        result = (True, func(*args, **kwds))
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 181, in hash_model_file
        legacy_hash = get_legacy_hash(metadata, filename)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 116, in get_legacy_hash
        return safetensors_hack.legacy_hash_file(filename)
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 80, in legacy_hash_file
        tensors, metadata = load_file(filename, "cpu")
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 41, in load_file
        return {name: create_tensor(storage, info, offset) for name, info in metadata.items() if name != "__metadata__"}, md
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 41, in <dictcomp>
        return {name: create_tensor(storage, info, offset) for name, info in metadata.items() if name != "__metadata__"}, md
      File "J:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 116, in create_tensor
        return torch.asarray(storage[start + offset : stop + offset], dtype=torch.uint8).view(dtype=dtype).reshape(shape).clone().detach()
    RuntimeError: self.size(-1) must be divisible by 4 to view Byte as Float (different element sizes), but got 124818

---

**Comment by NEXTAltair** [comment]
"I don't know the specifics, but when reusing configuration files with the command line arguments --ui-config-file and --ui-settings-file, there's a possibility that old settings could cause issues. By removing these two, I was able to resolve the problem."
