### ISSUE TITLE
sdxl lora run sd-webui-additional-networks

### ISSUE THREAD

**Issue by rookiexjl** [kohya-ss/sd-webui-additional-networks#232]
*** Error running process_batch: /root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
    Traceback (most recent call last):
      File "/root/autodl-tmp/stable-diffusion-webui/modules/scripts.py", line 643, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 244, in process_batch
        network, info = lora_compvis.create_network_and_apply_compvis(
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 153, in create_network_and_apply_compvis
        network = LoRANetworkCompvis(text_encoder, unet, multiplier_tenc, multiplier_unet, modules_dim, modules_alpha)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 341, in __init__
        comp_vis_lora_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(self.v2, du_lora_name)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 302, in convert_diffusers_name_to_compvis
        assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by `sd-scripts`."
    AssertionError: conversion failed: lora_te1_text_model_encoder_layers_0_mlp_fc1. the model may not be trained by `sd-scripts`.

**Comment by kalle07** [comment]
that error i get if i star automatc1111
............
D:\stable-diffusion\webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py:399: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
D:\stable-diffusion\webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py:521: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  cover_image = gr.Image(
Running on local URL:  http://127.0.0.1:7864
.............

and this if i enable network and chose 2 loras in the list

.............
LoRA weight_unet: 1, weight_tenc: 1, model: kalle07_010_cosine_iter2_ 000012_jugger_20epoches_adafactor_new2_32_16(71f40b64e0e4)
dimension: {32}, alpha: {16.0}, multiplier_unet: 1, multiplier_tenc: 1
*** Error running process_batch: D:\stable-diffusion\webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "D:\stable-diffusion\webui\modules\scripts.py", line 643, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "D:\stable-diffusion\webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 244, in process_batch
        network, info = lora_compvis.create_network_and_apply_compvis(
      File "D:\stable-diffusion\webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 153, in create_network_and_apply_compvis
        network = LoRANetworkCompvis(text_encoder, unet, multiplier_tenc, multiplier_unet, modules_dim, modules_alpha)
      File "D:\stable-diffusion\webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 341, in __init__
        comp_vis_lora_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(self.v2, du_lora_name)
      File "D:\stable-diffusion\webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 302, in convert_diffusers_name_to_compvis
        assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by `sd-scripts`."
    AssertionError: conversion failed: lora_te1_text_model_encoder_layers_0_mlp_fc1. the model may not be trained by `sd-scripts`.

---
.....................

**Comment by angelyz** [comment]
Restoring base VAE
Applying attention optimization: xformers... done.
VAE weights loaded.
LoRA weight_unet: 0.6, weight_tenc: 1, model: Came_v3_XL(3ea5e05f6643)
dimension: {128}, alpha: {128.0}, multiplier_unet: 0.6, multiplier_tenc: 1
*** Error running process_batch: C:\aki\AAPACKING\sd-webui-aki-v4.7.1\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "C:\aki\AAPACKING\sd-webui-aki-v4.7.1\modules\scripts.py", line 864, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "C:\aki\AAPACKING\sd-webui-aki-v4.7.1\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 244, in process_batch
        network, info = lora_compvis.create_network_and_apply_compvis(
      File "C:\aki\AAPACKING\sd-webui-aki-v4.7.1\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 153, in create_network_and_apply_compvis
        network = LoRANetworkCompvis(text_encoder, unet, multiplier_tenc, multiplier_unet, modules_dim, modules_alpha)
      File "C:\aki\AAPACKING\sd-webui-aki-v4.7.1\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 341, in __init__
        comp_vis_lora_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(self.v2, du_lora_name)
      File "C:\aki\AAPACKING\sd-webui-aki-v4.7.1\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 302, in convert_diffusers_name_to_compvis
        assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by `sd-scripts`."
    AssertionError: conversion failed: lora_unet_input_blocks_4_1_proj_in. the model may not be trained by `sd-scripts`.

**Comment by rookiexjl** [comment]
什么事
