### ISSUE TITLE
wire issue need help 'AssertionError: conversion failed: lora_unet_conv_in. the model may not be trained by `sd-scripts`.'

### ISSUE THREAD

**Issue by napoleonchn** [kohya-ss/sd-webui-additional-networks#241]
I encounter a wire issue, could not launch XYZ plot correctly, LORA don't work, all the image are the same, it shows, can anyone help me slove it?
LoRA weight_unet: 1, weight_tenc: 1, model: JiaQi_v3-000002(8cc5fdb62fe2)
dimension: {128, 64}, alpha: {64.0, 32.0}, multiplier_unet: 1, multiplier_tenc: 1
*** Error running process_batch: G:\sd-webui-aki-v4.2\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "G:\sd-webui-aki-v4.2\modules\scripts.py", line 742, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "G:\sd-webui-aki-v4.2\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 244, in process_batch
        network, info = lora_compvis.create_network_and_apply_compvis(
      File "G:\sd-webui-aki-v4.2\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 153, in create_network_and_apply_compvis
        network = LoRANetworkCompvis(text_encoder, unet, multiplier_tenc, multiplier_unet, modules_dim, modules_alpha)
      File "G:\sd-webui-aki-v4.2\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 341, in __init__
        comp_vis_lora_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(self.v2, du_lora_name)
      File "G:\sd-webui-aki-v4.2\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 302, in convert_diffusers_name_to_compvis
        assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by `sd-scripts`."
    AssertionError: conversion failed: lora_unet_conv_in. the model may not be trained by `sd-scripts`.

**Comment by jayododds** [comment]
also getting this on self trained loras. I'll try some Civitai downloads to confirm

**Comment by jayododds** [comment]
Civitai downloads seem to work for me - so it would seem there is something in the LORAs that I have created that is causing the issue. Likely a meta data issue or something of that nature - I'm looking into it. I'll let you know if I find anything that might help @napoleonchn, but don't hold your breath :)

**Comment by xenobyte-dev** [comment]
any solution? getting this on all my trained loras

**Comment by jayododds** [comment]
Hey @ToolB0xx  and @napoleonchn what are you training your models in? I had a couple that were trained on a mac with Draw Things - which work fine elsewhere but don't seem to work with this extension at all. I did a couple of new trainings with Kohya and they seem to work flawlessly. I think it comes down to what data is being saved in the .safetensor.

**Comment by ScrapWare** [comment]
I just encount this lora_conv_in issue may be not happens on simply up down mul(@)? this block only? have different not symmetric dim composition. However, finally this block dim is Conv2D 320 dims then needed reshape up down weight. These issue probably causing by dimension change with torch.linalg.SVD. May be not happens on pure trained LoRA so I seem merged LoRA throught SVD arranged dim... supermerger? I just encounted within change dim 64 to 128 merge code testing.

**Comment by ScrapWare** [comment]
lora_unet_conv_inはLycorisで起こります？他では起きておらず旧KohyaTrainerではalgo="lora"でしたがLycorisサイトではalgo="LoCon"となっていて、まだ試してないのでわかりませんが学習するかも知れません。一応LoHAとかでは起きてませんし通常LoRA〜LoCon(C3Lier)では起こらないようです。

普通に計算で問題なければ何もありませんかね。行列積おかしくなってdiag(S)で引っかかります。

lora_unet_conv_in: 64 to 32
down: torch.Size([64, 4, 3, 3])
up: torch.Size([320, 64, 1, 1])
↓  単にsqueeze()やreshapeなど
down:torch.Size([32, 36, 1, 1])
up:torch.Size([320, 32, 1, 1])

なのでreshapeでもviewきっかりで以下のようにすれば問題ないはず。他も叩き込みで引っかかるのありましたっけ。
```
s = down.shape
n = torch.Size([newdim, s[1], s[2], s[3]])
matmul(u, d).reshape(n)
```

以下のモデルキーにmatmul(@)〜からSVD等で問題なくなるかと。何故か@,torch.mm,torch.matmulではmatmul最速でたぶん次元の問題も起こさないかと。今度einsumもベンチしてみようかな。
`model.diffusion_model.input_blocks.0.0.weight: torch.Size([320, 4, 3, 3])`

学習してない問題と他とちょっと構成が違うので何かで計算コケるかも知れませんし、気づいたので記載しておきます。
