### ISSUE TITLE
additional network cann't work in SDXL 1.0 LORA.

### ISSUE THREAD

**Issue by littleyeson** [kohya-ss/sd-webui-additional-networks#244]
LoRA weight_unet: 0.5, weight_tenc: 0.5, model: LL_xl_v1.2(99135bb8a90f)
dimension: {64}, alpha: {8.0}, multiplier_unet: 0.5, multiplier_tenc: 0.5
*** Error running process_batch: C:\AI\sd-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "C:\AI\sd-webui\modules\scripts.py", line 808, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "C:\AI\sd-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 244, in process_batch
        network, info = lora_compvis.create_network_and_apply_compvis(
      File "C:\AI\sd-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 153, in create_network_and_apply_compvis
        network = LoRANetworkCompvis(text_encoder, unet, multiplier_tenc, multiplier_unet, modules_dim, modules_alpha)
      File "C:\AI\sd-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 341, in __init__
        comp_vis_lora_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(self.v2, du_lora_name)
      File "C:\AI\sd-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 302, in convert_diffusers_name_to_compvis
        assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by `sd-scripts`."
    AssertionError: conversion failed: lora_te1_text_model_encoder_layers_0_mlp_fc1. the model may not be trained by `sd-scripts`.

I use XL lora in additional network.there is error.How to fix it

**Comment by burialsjy** [comment]
Yes, I have the same problem, did you solve it

**Comment by psc0606** [comment]
same issue, not work for sdxl lora, sd1.5 loras work well.
