### ISSUE TITLE
Error loading script: additional_networks.py

### ISSUE THREAD

**Issue by mshpotak** [kohya-ss/sd-webui-additional-networks#28]
I get this error at launch. Any ideas?

```
Launching Web UI with arguments: --xformers --api --gradio-img2img-tool color-sketch
Error loading script: additional_networks.py
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\ai\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\ai\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 417, in <module>
    for script_class, path, basedir, script_module in scripts.scripts_data:
ValueError: not enough values to unpack (expected 4, got 3)
```

**Comment by kohya-ss** [comment]
Please update the Web UI to the latest version. The extension depends on the feature in the latest Web UI.

**Comment by mshpotak** [comment]
Alrighty, I pulled the latest version and the extension works now. Thanks!
I am pretty sure I tried this before I opened the issue though. Weird. Maybe it's because I reinstalled everything? Idk.
