### ISSUE TITLE
Error loading sript

### ISSUE THREAD

**Issue by Zedtec** [kohya-ss/sd-webui-additional-networks#36]
Hi i am getting the following error, what might be the issue ?

Error loading script: additional_networks.py
Traceback (most recent call last):
  File "F:\Super SD\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "F:\Super SD\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "F:\Super SD\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 421, in <module>
    model = xy_grid.AxisOption(f"AddNet Model {i+1}", str, lambda p, x, xs, i=i: apply_model(p, x, xs, i), format_lora_model, confirm_models)
TypeError: AxisOption.__new__() missing 1 required positional argument: 'cost'

**Comment by Tsukreya** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/d073637e104fa7256e0b0c546b5b83a16b881b8a broke it, scripts that use the XY grid now must specify a cost.

**Comment by Tsukreya** [comment]
Should be fixed now since the PR got merged.
