### ISSUE TITLE
TypeError: AxisOption.__new__() takes 6 positional arguments but 7 were given

### ISSUE THREAD

**Issue by MEIZU16** [kohya-ss/sd-webui-additional-networks#40]
additional_networks.py", line 421, in <module>
    model = xy_grid.AxisOption(f"AddNet Model {i+1}", str, lambda p, x, xs, i=i: apply_model(p, x, xs, i), format_lora_model, confirm_models, 0.5)
TypeError: AxisOption.__new__() takes 6 positional arguments but 7 were given
<img width="646" alt="image" src="https://user-images.githubusercontent.com/70087645/212914751-688d6cb1-d4ec-4ef2-a4fd-d4b77112b54d.png">

**Comment by St33lMouse** [comment]
Me too. But I checked my automatic1111 origin and did a git pull. problem solved:

git remote set-url origin https://github.com/AUTOMATIC1111/stable-diffusion-webui.git

**Comment by MEIZU16** [comment]
> 
But I have another problem after update

Error executing callback ui_tabs_callback for /home/dspwasc/Public/APT/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/home/dspwasc/Public/APT/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 284, in on_ui_tabs
    metadata_view = gr.JSON(value="test", label="Network metadata")
  File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 3523, in __init__
    IOComponent.__init__(
  File "/home/dspwasc/Public/APT/stable-diffusion-webui/modules/scripts.py", line 440, in IOComponent_init
    res = original_IOComponent_init(self, *args, **kwargs)
  File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 185, in __init__
    else self.postprocess(initial_value)
  File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 3567, in postprocess
    return json.loads(y)
  File "/root/miniconda3/envs/mutil/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/miniconda3/envs/mutil/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/miniconda3/envs/mutil/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dspwasc/Public/APT/stable-diffusion-webui/modules/script_callbacks.py", line 105, in ui_tabs_callback
    res += c.callback() or []
  File "/home/dspwasc/Public/APT/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 266, in on_ui_tabs
    with gr.Blocks(analytics_enabled=False) as additional_networks_interface:
  File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1097, in __exit__
    self.config = self.get_config_file()
  File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1073, in get_config_file
    "props": utils.delete_none(block.get_config())
  File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 3536, in get_config
    "value": self.value,
AttributeError: 'JSON' object has no attribute 'value'

**Comment by magicFeirl** [comment]
> > 
> 
> But I have another problem after update
> 
> Error executing callback ui_tabs_callback for /home/dspwasc/Public/APT/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py Traceback (most recent call last): File "/home/dspwasc/Public/APT/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 284, in on_ui_tabs metadata_view = gr.JSON(value="test", label="Network metadata") File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 3523, in **init** IOComponent.**init**( File "/home/dspwasc/Public/APT/stable-diffusion-webui/modules/scripts.py", line 440, in IOComponent_init res = original_IOComponent_init(self, *args, **kwargs) File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 185, in **init** else self.postprocess(initial_value) File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 3567, in postprocess return json.loads(y) File "/root/miniconda3/envs/mutil/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/root/miniconda3/envs/mutil/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/root/miniconda3/envs/mutil/lib/python3.10/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/dspwasc/Public/APT/stable-diffusion-webui/modules/script_callbacks.py", line 105, in ui_tabs_callback res += c.callback() or [] File "/home/dspwasc/Public/APT/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 266, in on_ui_tabs with gr.Blocks(analytics_enabled=False) as additional_networks_interface: File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1097, in **exit** self.config = self.get_config_file() File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1073, in get_config_file "props": utils.delete_none(block.get_config()) File "/home/dspwasc/Public/APT/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 3536, in get_config "value": self.value, AttributeError: 'JSON' object has no attribute 'value'

You may need to check back to a old version of web ui:
`!git checkout -f 8e2aeee4a127b295bfc880800e4a312e0f049b85`
I use this and It's works.

Also see #38 , I am using this version of sd-webui-additional-networks

**Comment by kohya-ss** [comment]
Hi, the recent update #44  will fix the error ``AttributeError: 'JSON' object has no attribute 'value'``.

If you update the web UI, please also update the extension.
