### ISSUE TITLE
issue with latest committ auto committ 51517f3ea668f37408be7224dc6c35ef57cf92d9

### ISSUE THREAD

**Issue by gsgoldma** [kohya-ss/sd-webui-additional-networks#46]
Error running process: D:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 347, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 238, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight, text_encoder, unet)
  File "D:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 72, in create_network_and_apply_compvis
    size = du_state_dict[list(du_state_dict.keys())[0]].size()          # if conv2d size is like [320,4,1,1]
AttributeError: 'tuple' object has no attribute 'size'

getting distorted results

**Comment by kohya-ss** [comment]
Hi,
It appears you are trying to load a model file that was not trained with ``sd-scripts``. Please check if the model file was trained with ``sd-scripts``.
