### ISSUE TITLE
AssertionError: conversion failed: cond_stage_model

### ISSUE THREAD

**Issue by CAPT15** [kohya-ss/sd-webui-additional-networks#47]
Benn getting this error whenever I try to generate an image with a lora. Anyone know what this or how to fix it?

Error running process: D:\Downloads\Diffusion\TRYING AGAIN\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "D:\Downloads\Diffusion\TRYING AGAIN\stable-diffusion-webui\modules\scripts.py", line 347, in process
    script.process(p, *script_args)
  File "D:\Downloads\Diffusion\TRYING AGAIN\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 238, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight, text_encoder, unet)
  File "D:\Downloads\Diffusion\TRYING AGAIN\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 78, in create_network_and_apply_compvis
    state_dict = network.apply_lora_modules(du_state_dict)              # some weights are applied to text encoder
  File "D:\Downloads\Diffusion\TRYING AGAIN\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 246, in apply_lora_modules
    state_dict = LoRANetworkCompvis.convert_state_dict_name_to_compvis(self.v2, du_state_dict)
  File "D:\Downloads\Diffusion\TRYING AGAIN\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 152, in convert_state_dict_name_to_compvis
    compvis_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(v2, tokens[0])
  File "D:\Downloads\Diffusion\TRYING AGAIN\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 141, in convert_diffusers_name_to_compvis
    assert cv_name is not None, f"conversion failed: {du_name}"
AssertionError: conversion failed: cond_stage_model

**Comment by kohya-ss** [comment]
Hi, 
It appears that you are trying to load a Stable Diffusion model file, not a LoRA model file. Please check the model file to load.

**Comment by CAPT15** [comment]
> o load a Stable Diffusion model file, not a LoRA model file. Please check the mode

Thanks for responding. I am pretty sure that I'm trying to load a LoRA file: specifically, I am trying to load AbyssOrangeMix2_hard.safetensors, but everytime I try, that error pops up. It's also only started happening once I updated both this and web-ui, before that, it worked fine.

**Comment by CAPT15** [comment]
... actually that probably means that it's an issue with AOM, not this. Sorry about that!
