### ISSUE TITLE
issue with loading models

### ISSUE THREAD

**Issue by jilask** [kohya-ss/sd-webui-additional-networks#52]
I use google colab and I tried to load a lora model for first time and it gave me this error.

Total progress: 0it [00:00, ?it/s]LoRA weight: 1, model: hinataHyuugaLora_hinata(e3b0c442)
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 347, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 234, in process
    du_state_dict = load_file(model_path)
  File "/usr/local/lib/python3.8/dist-packages/safetensors/torch.py", line 98, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
Exception: Error while deserializing header: HeaderTooSmall

**Comment by laobenmao** [comment]
I met the same problem today.
