### ISSUE TITLE
I get an error when using Lora (when generating images using Lora), but I don't know what to do about it! Please help!!! (compVIS or torch problem?)

### ISSUE THREAD

**Issue by zundamon075** [kohya-ss/sd-webui-additional-networks#53]
I am getting these errors

LoRA weight: 2, model: suzuka_san_kansei(aa86e195)
dimension: None, alpha: None, multiplier: 2
Error running process: /notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 347, in process
    script.process(p, *script_args)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 238, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight, text_encoder, unet)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 96, in create_network_and_apply_compvis
    network = LoRANetworkCompvis(text_encoder, unet, multiplier=multiplier, lora_dim=network_dim, alpha=network_alpha)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 233, in __init__
    self.text_encoder_loras, te_rep_modules = create_modules(LoRANetworkCompvis.LORA_PREFIX_TEXT_ENCODER,
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 214, in create_modules
    lora = LoRAModule(lora_name, child_module, self.multiplier, self.lora_dim, self.alpha)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 41, in __init__
    self.lora_down = torch.nn.Linear(in_dim, lora_dim, bias=False)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

**Comment by zundamon075** [comment]
LoRA weight: 2, model: suzuka_san_kansei(aa86e195)
dimension: None, alpha: None, multiplier: 2
Error running process: /notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 347, in process
    script.process(p, *script_args)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 238, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight, text_encoder, unet)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 96, in create_network_and_apply_compvis
    network = LoRANetworkCompvis(text_encoder, unet, multiplier=multiplier, lora_dim=network_dim, alpha=network_alpha)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 233, in __init__
    self.text_encoder_loras, te_rep_modules = create_modules(LoRANetworkCompvis.LORA_PREFIX_TEXT_ENCODER,
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 214, in create_modules
    lora = LoRAModule(lora_name, child_module, self.multiplier, self.lora_dim, self.alpha)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 41, in __init__
    self.lora_down = torch.nn.Linear(in_dim, lora_dim, bias=False)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

**Comment by zundamon075** [comment]
Self -contained! (The file used was not a Lora file)
