### ISSUE TITLE
additional-networks option isn't visible

### ISSUE THREAD

**Issue by vedereRohit** [kohya-ss/sd-webui-additional-networks#55]
additional-networks option isn't visible no more on auto11 web UI after the new update,any fix?
![Screenshot (158)](https://user-images.githubusercontent.com/74318245/213982949-a8e34898-dcc0-4343-9262-c0e133c0b88d.png)

**Comment by emrk30** [comment]
Same, can't seem to find the Additional Networks tab after installing it. I'm quite new to this so I might be doing something wrong, but anyway I have the same problem!

**Comment by Sp00ch** [comment]
Im having this problem as well, Im getting this error. Im also very new to this, so this might as well be a foreign language.
![image](https://user-images.githubusercontent.com/123526344/214470311-fc683deb-b60b-4273-8cd3-da1bdd7d037f.png)

**Comment by vegacosphoto** [comment]
same here

**Comment by wrathgoddess** [comment]
try to use https://github.com/kohya-ss/sd-webui-additional-networks/tree/dev2

**Comment by Shaiktit** [comment]
i did this and it is still not appearing
![image](https://user-images.githubusercontent.com/121429408/215733319-40f6699d-f135-4427-926b-42be5db36c8e.png)
![image](https://user-images.githubusercontent.com/121429408/215733408-f2159807-536b-4db7-a9fd-0a32dc789eb6.png)


> try to use https://github.com/kohya-ss/sd-webui-additional-networks/tree/dev2

**Comment by wrathgoddess** [comment]
I move the scrips into the original folder it looks like this 
![Screenshot 2023-02-01 025417](https://user-images.githubusercontent.com/109845363/215996161-088cf9b9-4738-4f17-9ad8-48eab62136ae.png)

**Comment by wrathgoddess** [comment]
im not sure how it all works but this what fixed mine

**Comment by tpcdaz** [comment]
No matter what I do I cannot get Additional Networks tab to show. Yes I've tried Dev2. I've tried having both installed, one installed, older versions. Nothing.

**Comment by emrk30** [comment]
Here's how I fixed it. I first added git pull to my webui-user.bat to always keep SD webui updated. Once it's updated I closed ti and removed manually the sd-webui-additional-networks folder. And then restart webui and redid the installation process for additionnal networks from the start and it worked this time without a problem!

**Comment by myrzx** [comment]
I update torch vision from 1.11.0 to 1.12.1, then it work.

> pip install  torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113

You can try it if your log is
> Error loading script: additional_networks.py
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/root/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 11, in <module>
    from scripts import lora_compvis, model_util, metadata_editor, xyz_grid_support
  File "/root/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/model_util.py", line 12, in <module>
    from scripts import safetensors_hack, model_util, util
  File "/root/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/safetensors_hack.py", line 13, in <module>
    UntypedStorage = torch.storage.UntypedStorage if hasattr(torch.storage, 'UntypedStorage') else torch.storage._UntypedStorage
AttributeError: module 'torch.storage' has no attribute '_UntypedStorage'
