### ISSUE TITLE
can't load extention

### ISSUE THREAD

**Issue by ShakedBaws** [kohya-ss/sd-webui-additional-networks#68]
C:\Users\shake\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: ansformers is an invalid version and will not be supported in a future release
  warnings.warn(
Error loading script: additional_networks.py
Traceback (most recent call last):
  File "C:\Users\shake\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\shake\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\shake\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 20, in <module>
    from modules import shared, sd_models, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)

**Comment by wrathgoddess** [comment]
try to use https://github.com/kohya-ss/sd-webui-additional-networks/tree/dev2

**Comment by lomyc** [comment]
still cant work
Traceback (most recent call last):
  File "C:\acd\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\acd\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\acd\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 11, in <module>
    from scripts import lora_compvis, model_util, metadata_editor, xyz_grid_support
  File "C:\acd\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 11, in <module>
    from modules import shared, sd_models, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)

Error loading script: metadata_editor.py
Traceback (most recent call last):
  File "C:\acd\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\acd\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\acd\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py", line 14, in <module>
    from modules.ui_components import ToolButton
ModuleNotFoundError: No module named 'modules.ui_components'

Error loading script: model_util.py
Traceback (most recent call last):
  File "C:\acd\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\acd\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\acd\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 11, in <module>
    from modules import shared, sd_models, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)

Error loading script: safetensors_hack.py
Traceback (most recent call last):
  File "C:\acd\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\acd\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\acd\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\safetensors_hack.py", line 7, in <module>
    import safetensors
ModuleNotFoundError: No module named 'safetensors'

Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "C:\acd\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\acd\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\acd\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\xyz_grid_support.py", line 5, in <module>
    from scripts import model_util, util
  File "C:\acd\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 11, in <module>
    from modules import shared, sd_models, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)
