### ISSUE TITLE
Error loading script: additional_networks.py

### ISSUE THREAD

**Issue by imacopypaster** [kohya-ss/sd-webui-additional-networks#80]
```
Error loading script: additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 159, in <module>
    def split_path_list(path_list: str) -> list[str]:
TypeError: 'type' object is not subscriptable
```
![image](https://user-images.githubusercontent.com/45368535/215613963-f06c1d30-0c3f-4f33-b602-3bd37764fe90.png)

(on actual version A1111)

**Comment by wrathgoddess** [comment]
use the dev2 branch https://github.com/kohya-ss/sd-webui-additional-networks/tree/dev2. new update don't work for us

**Comment by imacopypaster** [comment]
Thanks, [wrathgoddess](https://github.com/wrathgoddess)

**Comment by CoolSave** [comment]
Hi, how i can clone the dev2 version in colab ? I put the link https://github.com/kohya-ss/sd-webui-additional-networks/tree/dev2 but it says "not found", what im doing wrong ?.

**Comment by kohya-ss** [comment]
Thank you for the workaround. The latest version might be working on Python 3.8, and dev2 branch will be removed in near future.

**Comment by Shaiktit** [comment]
> Hi, how i can clone the dev2 version in colab ? I put the link https://github.com/kohya-ss/sd-webui-additional-networks/tree/dev2 but it says "not found", what im doing wrong ?.

same im getting the not found error as well. i tried zipping it and pasting its still not working for me

**Comment by imacopypaster** [comment]
> Hi, how i can clone the dev2 version in colab ? I put the link https://github.com/kohya-ss/sd-webui-additional-networks/tree/dev2 but it says "not found", what im doing wrong ?.

```
!wget -q https://github.com/kohya-ss/sd-webui-additional-networks/archive/refs/heads/dev2.zip
!unzip -n -q dev2.zip -d /content/stable-diffusion-webui/extensions && rm dev2.zip
```

**Comment by Shaiktit** [comment]
> > Hi, how i can clone the dev2 version in colab ? I put the link https://github.com/kohya-ss/sd-webui-additional-networks/tree/dev2 but it says "not found", what im doing wrong ?.
> 
> ```
> !wget -q https://github.com/kohya-ss/sd-webui-additional-networks/archive/refs/heads/dev2.zip
> !unzip -n -q dev2.zip -d /content/stable-diffusion-webui/extensions && rm dev2.zip
> ```

still doesnt work for me.

**Comment by imacopypaster** [comment]
> still doesnt work for me.

Make sure that the archive is unpacked to the right path.
It all depends on what kind of colab you use, of course.
For example TheLastBen's colab use non-standard paths to folders, so adjust the path to suit your colab.
![image](https://user-images.githubusercontent.com/45368535/215989083-a99ddaca-709e-4132-972b-b8e4c05d3dac.png)

**Comment by wrathgoddess** [comment]
> Thank you for the workaround. The latest version might be working on Python 3.8, and dev2 branch will be removed in near future.

im on 3.10.6 is that the reason the update not compatible?

**Comment by ExiaCyn** [comment]
Exact same problem, all the fixes suggested have also failed to fix the issue. I'm using python 3.10.8 and ensured it was a clean install. Script also fails to load.
I installed it on runpod and they seem to be running 3.10.9 so it seems unlikely it's the python version. Must be something else to do with either windows or the build.

**Comment by AlizerUncaged** [comment]
Still got this issue as well, any fixes yet?

**Comment by AlizerUncaged** [comment]
Alright so it works for me now I decided to come back to this thread hopefully I can help someone. Basically I went to the stable diffusion folder (the same folder where a folder named ".git" exists too), I opened up `cmd` and ran a `git pull`, not `git fetch`, just a `git pull`, that's when I realized my WebUI was very out of date, the UI looked so different from the old one I had which hasn't been update since November 2022.
