### ISSUE TITLE
After fresh install: Error: "AxisOption.__new__() got an unexpected keyword argument 'cost'" and no extra tab

### ISSUE THREAD

**Issue by Xelgardi** [kohya-ss/sd-webui-additional-networks#93]
I just installed this extension in A1111's Web UI and after restarting I was wondering why the "additional networks" tab isn't showing up. 
Upon checking the commandline I found the following error:
```
Error loading script: additional_networks.py
Traceback (most recent call last):
  File "D:\stable-diffusion-2\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-2\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-2\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 268, in <module>
    xyz_grid_support.initialize(Script)
  File "D:\stable-diffusion-2\extensions\sd-webui-additional-networks\scripts\xyz_grid_support.py", line 156, in initialize
    model = xy_grid.AxisOption(f"AddNet Model {i+1}", str, lambda p, x, xs, i=i: apply_model(p, x, xs, i), format_lora_model, confirm_models, cost=0.5, choices=lambda i=i: get_axis_model_choices(i))
TypeError: AxisOption.__new__() got an unexpected keyword argument 'cost'
```

This in on torch 1.13.1 on A1111 GUI version from February 5 (latest at time of writing).

**Comment by Xelgardi** [comment]
I resolved this by making a completly fresh install of A1111s Web UI and installing this extension then. No idea what's wrong with the old Installation though.
