### ISSUE TITLE
Error loading script: additional_networks.py

### ISSUE THREAD

**Issue by amamoemomo** [kohya-ss/sd-webui-additional-networks#94]
Reloading extensions
Reloading custom scripts
Error loading script: additional_networks.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 11, in <module>
    from scripts import lora_compvis, model_util, metadata_editor, xyz_grid_support
  File "C:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 11, in <module>
    from modules import shared, sd_models, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)

Error loading script: metadata_editor.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py", line 14, in <module>
    from modules.ui_components import ToolButton
ModuleNotFoundError: No module named 'modules.ui_components'

Error loading script: model_util.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 11, in <module>
    from modules import shared, sd_models, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)

Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\xyz_grid_support.py", line 5, in <module>
    from scripts import model_util, util
  File "C:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 11, in <module>
    from modules import shared, sd_models, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)

**Comment by amamoemomo** [comment]
I tried to install the extension but the extensions tab did not come up. 
I saw the error and the above message was output, but it seems to be an import error.
 I would like to know the solution or recommended environment as I do not know the cause.
Python revision: 3.10.6

**Comment by Mudereded401** [comment]
Something like that happened to me. It appeared to me because the format of the LoRA models wasn't correct. Try checking the formats of your models (ckpt or .safetensors) and where you downloaded them.

**Comment by amamoemomo** [comment]
Thank you for your response.
I have checked and it appears that the placement is correct.
However, I cannot use LoRA because the Addtional Networks tab does not appear in the first place.
I have followed steps 1-5 of the installation procedure, but I am getting the above error and would like to know if there is a solution to this problem.

**Comment by Slefishgenii** [comment]
I also cannot use LoRA because the Addtional Networks tab is missing, it is installed but it's not showing up (updated and restarted)

**Comment by Mudereded401** [comment]
Have you tried downloading an older version? Also you can try downloading Dev2: https://github.com/kohya-ss/sd-webui-additional-networks/archive/refs/heads/dev2.zip

**Comment by Slefishgenii** [comment]
yes, i'm not managing to have any option to use lora with those 2 versions

Error loading script: additional_networks.py
Traceback (most recent call last):
  File "C:\Users\...\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\...\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\...\stable-diffusion-webui\extensions\sd-webui-additional-networks-dev2\scripts\additional_networks.py", line 432, in <module>
    model = xy_grid.AxisOption(f"AddNet Model {i+1}", str, lambda p, x, xs,
TypeError: AxisOption.__new__() takes 6 positional arguments but 7 were given

**Comment by Slefishgenii** [comment]
I did a fresh install of automatic1111 and its solved, changed the base folder location also, i don't know if it was the reason.

**Comment by amamoemomo** [comment]
Thank you for your response. I updated automatic1111 using the method in the URL you described and the error is gone and the Addtional Networks tab is now displayed.
[https://economylife.net/update-git-stable-diffusion-webui-automatic1111/](url)

**Comment by Best-by-feb132024** [comment]
Having the same issue and a fresh install / trying the dev2 version above didn't fix it.
Any other methods? I did reinstall by downloading the github .zip file and extracting to my directory if that effects it.

Only other idea may be that im on python 3.9.12 and not 3.10.6, but I don't know how to upgrade it without overwriting my systems 3.11 python ver

**Comment by ArtificialOtaku** [comment]
I just updated the webui today, and I'm still getting this error. I don't get any "additional netwroks" tab, only the "extra networks" one.

**Comment by Best-by-feb132024** [comment]
Just updated to python 3.10.6 and still no dice

````
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Error loading script: additional_networks.py
Traceback (most recent call last):
  File "N:\stable_diffusion\stable-diffusion-webui-master\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "N:\stable_diffusion\stable-diffusion-webui-master\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "N:\stable_diffusion\stable-diffusion-webui-master\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 291, in <module>
    xyz_grid_support.initialize(Script)
  File "N:\stable_diffusion\stable-diffusion-webui-master\extensions\sd-webui-additional-networks\scripts\xyz_grid_support.py", line 156, in initialize
    model = xy_grid.AxisOption(f"AddNet Model {i+1}", str, lambda p, x, xs, i=i: apply_model(p, x, xs, i), format_lora_model, 
confirm_models, cost=0.5, choices=lambda i=i: get_axis_model_choices(i))

TypeError: AxisOption.__new__() got an unexpected keyword argument 'cost'
````

**Comment by Woisek** [comment]
I experience an error that seem a bit different, but idk ...

Error executing callback ui_tabs_callback for I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "I:\Super SD 2.0\stable-diffusion-webui\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 232, in on_ui_tabs
    metadata_editor.setup_ui(addnet_paste_params)
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py", line 384, in setup_ui
    send_to_button.click(fn=lambda modu, mod: (modu, model_util.find_closest_lora_model_name(mod) or "None"), inputs=[module, model], outputs=[addnet_paste_params[tabname][i]["module"], addnet_paste_params[tabname][i]["model"]])
IndexError: list index out of range

Error executing callback ui_tabs_callback for I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "I:\Super SD 2.0\stable-diffusion-webui\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 232, in on_ui_tabs
    metadata_editor.setup_ui(addnet_paste_params)
  File "I:\Super SD 2.0\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py", line 384, in setup_ui
    send_to_button.click(fn=lambda modu, mod: (modu, model_util.find_closest_lora_model_name(mod) or "None"), inputs=[module, model], outputs=[addnet_paste_params[tabname][i]["module"], addnet_paste_params[tabname][i]["model"]])
IndexError: list index out of range

Running on local URL:  http://127.0.0.1:7860

**Comment by AlizerUncaged** [comment]
I also get this error? any fixes?
```
Error loading script: additional_networks.py
Traceback (most recent call last):
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 11, in <module>
    from scripts import lora_compvis, model_util, metadata_editor, xyz_grid_support
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 11, in <module>
    from modules import shared, sd_models, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)

Error loading script: metadata_editor.py
Traceback (most recent call last):
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py", line 18, in <module>
    from scripts import safetensors_hack, model_util
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 11, in <module>
    from modules import shared, sd_models, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)

Error loading script: model_util.py
Traceback (most recent call last):
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 11, in <module>
    from modules import shared, sd_models, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)

Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\xyz_grid_support.py", line 5, in <module>
    from scripts import model_util, util
  File "D:\automatic 111 stable diffusion\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\model_util.py", line 11, in <module>
    from modules import shared, sd_models, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)
```

**Comment by if-ai** [comment]
Ihave the same error on win 10, I already unzipped Dev2: and replaced the script but the problem persist. https://github.com/kohya-ss/sd-webui-additional-networks/archive/refs/heads/dev2.zip Launching Web UI with arguments: --api --xformers --no-half
Error loading script: additional_networks.py
Traceback (most recent call last):
  File "E:\DB\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\DB\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\DB\stable-diffusion-webui\scripts\additional_networks.py", line 11, in <module>
    from scripts import lora_compvis, model_util, metadata_editor, xyz_grid_support
ImportError: cannot import name 'model_util' from 'scripts' (unknown location)
