### ISSUE TITLE
failing to load/edit metadata on some new models

### ISSUE THREAD

**Issue by Robonau** [kohya-ss/sd-webui-additional-networks#97]
![TzF4LNE](https://user-images.githubusercontent.com/30987265/217854963-ce72aade-e41f-41f4-9cee-8a8baf4ad86f.png)

lora: [https://civitai.com/models/7466](url)

apparently made using the "latest kohya trainer"
as mentioned in [https://civitai.com/models/7466?commentId=21696&modal=commentThread](url)

```Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/metadata_editor.py", line 249, in refresh_metadata
    count_max = max(top_tags.values())
ValueError: max() arg is an empty sequence
```
is the error in console

is only happening with vary new loras
older ones still load and edit metadata fine

**Comment by kohya-ss** [comment]
Thank you for reporting. I will check it.

**Comment by kohya-ss** [comment]
I've fixed a bug. Please update the extension.

The model trained with the metadata json and there is no tag in the metadata, the model has the empty tag frequency, and it crashes the metadata editor.
